// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations hold a database lock while they run. Neon's pooled address
    // ("-pooler" in the host) can send the unlock down a different
    // connection, leaving the lock behind, and the next deploy then fails
    // with P1002. So migrations use the direct address; the app stays pooled.
    url: process.env["DATABASE_URL"]?.replace("-pooler.", "."),
  },
});
